source 'https://rubygems.org'

gem 'rake'
gem 'test-unit'
gem 'dotenv'
gem 'nokogiri'
gem 'sequel'
gem 'pg'
gem 'dropbox_api'
gem 'mongo'
gem 'bson_ext'
gem 'neatjson'
gem 'colorize'
gem 'google_maps_service'
gem 'parallel'
gem 'sinatra'